version: '3'
services:
  core:
    build:
      context: server
      dockerfile: Dockerfile.dev
    ports:
     - "3002:3002"
    environment:
     - NODE_ENV=development
    volumes:
     - "./server:/usr/src/app"
  webapp:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    ports:
     - "8080:8080"
     - "8081:8081"
    volumes:
    - "./frontend:/usr/src/app"
